name: momochari
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  html: ^0.15.4
  http: ^1.2.1
  charset_converter: ^2.2.0
  google_maps_flutter: ^2.6.1
  envied: ^0.5.4+1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.gif
    - assets/port_image/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"